apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-statsd-exporter.fullname" . }}
  labels:
{{ include "prometheus-statsd-exporter.labels" . | indent 4 }}
data:
{{- if .Values.statsd.mappingConfig }}
  statsd.mappingConf: |
{{ .Values.statsd.mappingConfig | indent 4 }}
{{- end }}
