apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-statsd-exporter.fullname" . }}
  labels:
    {{- include "prometheus-statsd-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus-statsd-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prometheus-statsd-exporter.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "prometheus-statsd-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --web.listen-address=:{{ .Values.web.port }}
            - --web.telemetry-path={{ .Values.web.path }}
            {{- if .Values.statsd.udpPort }}
            - --statsd.listen-udp=:{{ .Values.statsd.udpPort }}
            {{- else }}
            - --statsd.listen-udp=
            {{- end }}
            {{- if .Values.statsd.tcpPort }}
            - --statsd.listen-tcp=:{{ .Values.statsd.tcpPort }}
            {{- else }}
            - --statsd.listen-tcp=
            {{- end }}
            - --statsd.cache-size={{ .Values.statsd.cacheSize }}
            - --statsd.event-queue-size={{ .Values.statsd.eventQueueSize }}
            - --statsd.event-flush-threshold={{ .Values.statsd.eventFlushThreshold }}
            - --statsd.event-flush-interval={{ .Values.statsd.eventFlushInterval }}
            {{- if .Values.statsd.mappingConfig }}
            - --statsd.mapping-config=/etc/prometheus-statsd-exporter/statsd-mapping.conf
            {{- end }}
          ports:
            - name: web
              containerPort: {{ .Values.web.port }}
              protocol: TCP
            {{- if .Values.statsd.tcpPort }}
            - name: statsd-tcp
              containerPort: {{ .Values.statsd.tcpPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.statsd.udpPort }}
            - name: statsd-udp
              containerPort: {{ .Values.statsd.udpPort }}
              protocol: UDP
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.path }}
              port: web
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.statsd.mappingConfig }}
          volumeMounts:
          - name: statsd-mapping-config
            mountPath: /etc/prometheus-statsd-exporter
      volumes:
      - name: statsd-mapping-config
        configMap:
          name: {{ template "prometheus-statsd-exporter.fullname" . }}
          items:
          - key: statsd.mappingConf
            path: statsd-mapping.conf
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
